services:
  blog:
    # 告诉 Docker Compose 使用当前目录下的 Dockerfile 来构建镜像
    build: .
    # 给构建出的镜像起个名字
    image: ethanlauy-blog:latest
    container_name: ethanlauy-blog
    # 连接到我们之前创建的外部 nginx-proxy 网络
    networks:
      - nginx-proxy
    # 设置环境变量，让 nginx-proxy 知道如何路由流量
    environment:
      - VIRTUAL_HOST=liuhongwei.org
      - LETSENCRYPT_HOST=liuhongwei.org
    restart: unless-stopped

networks:
  nginx-proxy:
    # 声明这是一个已经存在的外部网络
    external: true