# 使用官方 Python 镜像作为基础镜像
FROM python:3.11-slim

# 设置环境变量，防止 Python 写入 .pyc 文件
ENV PYTHONDONTWRITEBYTECODE 1
# 设置环境变量，确保 Python 输出是无缓冲的
ENV PYTHONUNBUFFERED 1

# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt .

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目文件
COPY . .

# 暴露 Django 开发服务器端口
EXPOSE 8000

# 运行开发服务器
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
