# Generated by Django 5.1.7 on 2025-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tldr',
            field=models.CharField(blank=True, help_text='简介，可选', max_length=500, null=True),
        ),
    ]
