# Generated by Django 5.1.7 on 2025-10-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tldr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tldr',
            field=models.CharField(blank=True, help_text='A short summary of the post.', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
