# Generated by Django 5.1.7 on 2026-05-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_idea_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(help_text='仅支持纯文本，不支持 Markdown'),
        ),
        migrations.CreateModel(
            name='IdeaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.idea')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
